import React from "react";
import { Metadata } from "next";
import "../globals.css";
import Header from "@/components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, leftSidebar,rightSidebar }) {
  return (
    <div>
      <Header />
      <div className="w-full h-[calc(100vh-10vh)] flex flex-row">
        <div className="w-[20%]">{leftSidebar}</div>
        <div className="w-full">{children}</div>
        <div className="w-[40%]">{rightSidebar}</div>
      </div>
    </div>
  );
}
